### ISSUE TITLE
Get citation count at a given time

### ISSUE THREAD

**Issue by VJalili** [pybliometrics-dev/pybliometrics#123]
Is there any method or API to get citation count at a given time? e.g., how many times the article with DOI XYZ was cited through 2016 (since it's publication date to 2016).

**Comment by Michael-E-Rose** [comment]
You can use the Citation Overview API to accomplish this: https://pybliometrics.readthedocs.io/en/stable/examples/CitationOverview.html

**Comment by VJalili** [comment]
Using that method I get `403 Client Error`. 

I am using the following code (from the documentation page):

```python
from pybliometrics.scopus import CitationOverview
co = CitationOverview("2-s2.0-84930616647", start=2015, end=2017)
```

and I get the following error:

```shell
Traceback (most recent call last):
  File ".\main.py", line 2, in <module>
    co = CitationOverview("2-s2.0-84930616647", start=2015, end=2017)
  File "...\pybliometrics\scopus\abstract_citations.py", line 168, in __init__
    date=date)
  File "...\pybliometrics\scopus\classes\retrieval.py", line 60, in __init__
    res = get_content(qfile, refresh, url=url, params=params)
  File "...\pybliometrics\scopus\utils\get_content.py", line 165, in get_content
    content = cache_file(*args, **kwds).text.encode('utf-8')
  File "...\pybliometrics\scopus\utils\get_content.py", line 92, in cache_file
    resp.raise_for_status()
  File "...\Python37-32\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.elsevier.com/content/abstract/citations/2-s2.0-84930616647?view=STANDARD&date=2015-2017&scopus_id=84930616647
```

**Comment by Michael-E-Rose** [comment]
Yes, see the second sentence in the docs. You need special permission by Scopus for this API. Your local Scopus salesperson can help you.
