### ISSUE TITLE
Scopus429Error quota exceeded error is without description

### ISSUE THREAD

**Issue by raffaem** [pybliometrics-dev/pybliometrics#158]
The exception pybliometrics.scopus.exception.Scopus429Error comes without a desciption. Here is the output:

```
Traceback (most recent call last):
  File "main.py", line 59, in <module>
    download_authorid(str(pot_app), msg)
  File "main.py", line 27, in download_authorid
    res = ScopusSearch(query, subscriber=True, download=True, verbose=True)
  File "C:\Users\Raffaele\anaconda3\lib\site-packages\pybliometrics\scopus\scopus_search.py", line 198, in __init__
    Search.__init__(self, query=query, api='ScopusSearch', refresh=refresh,
  File "C:\Users\Raffaele\anaconda3\lib\site-packages\pybliometrics\scopus\superclasses\search.py", line 76, in __init__
    Base.__init__(self, qfile, refresh, params=params, url=SEARCH_URL[api],
  File "C:\Users\Raffaele\anaconda3\lib\site-packages\pybliometrics\scopus\superclasses\base.py", line 70, in __init__
    resp = get_content(url, params, *args, **kwds)
  File "C:\Users\Raffaele\anaconda3\lib\site-packages\pybliometrics\scopus\utils\get_content.py", line 86, in get_content
    raise errors[resp.status_code](reason)
pybliometrics.scopus.exception.Scopus429Error
```

I would expected the output pybliometrics.scopus.exception.Scopus429Error to be followed by a more useful description, like "quota exceeded"

**Comment by Michael-E-Rose** [comment]
Yes, this should normally be the case: Pybliometrics tries to give the reason provided by Scopus. It is handled in https://github.com/pybliometrics-dev/pybliometrics/blob/master/pybliometrics/scopus/utils/get_content.py#L76-L88. 

But for some reason, recently Scopus sometimes (always?) returns xml instead of json when the quota is exceeded. Since we don't use xml parsing any more, pybliometrics simply raises the error w/o further explanation. Scopus is aware of this anomaly.
