### ISSUE TITLE
Scopus400Error for ordinary query

### ISSUE THREAD

**Issue by Michael-E-Rose** [pybliometrics-dev/pybliometrics#170]
```
>>> query = "INDEXTERMS(BRAIN OR AI OR ARTIFICIAL INTELLIGENCE)"
>>> s = ScopusSearch(query, download=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pybliometrics/scopus/scopus_search.py", line 200, in __init__
    download=download, verbose=verbose, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/pybliometrics/scopus/superclasses/search.py", line 77, in __init__
    download=download, max_entries=max_entries, verbose=verbose)
  File "/usr/local/lib/python3.6/dist-packages/pybliometrics/scopus/superclasses/base.py", line 70, in __init__
    resp = get_content(url, params, *args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/pybliometrics/scopus/utils/get_content.py", line 87, in get_content
    raise errors[resp.status_code](reason)
pybliometrics.scopus.exception.Scopus400Error: Use of certain field restrictions in the search query is not allowed for this requestor.
```
Should yield 320k documents, but it's not even getting the number of results.

**Comment by Michael-E-Rose** [comment]
It fails because `INDEXTERMS()` is restricted.

Documentation updated in e3e803b1223c793ae82cf74e3216de0ce8560a56.
