### ISSUE TITLE
Scopus404Error on CitationOverview

### ISSUE THREAD

**Issue by raffaem** [pybliometrics-dev/pybliometrics#204]
My API key was enabled for Citation Overview API  (otherwise it would throw 403, not 404)

```
>>> c = CitationOverview(identifier="85078218772", start=2010)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/raffaele/.local/lib/python3.9/site-packages/pybliometrics/scopus/abstract_citation.py", line 273, in __init__
    Retrieval.__init__(self, stem, api='CitationOverview', date=date,
  File "/home/raffaele/.local/lib/python3.9/site-packages/pybliometrics/scopus/superclasses/retrieval.py", line 48, in __init__
    Base.__init__(self, params=params, url=url, api=api)
  File "/home/raffaele/.local/lib/python3.9/site-packages/pybliometrics/scopus/superclasses/base.py", line 59, in __init__
    resp = get_content(url, api, params, *args, **kwds)
  File "/home/raffaele/.local/lib/python3.9/site-packages/pybliometrics/scopus/utils/get_content.py", line 97, in get_content
    raise errors[resp.status_code](reason)
pybliometrics.scopus.exception.Scopus404Error: The resource specified cannot be found.
```

**Comment by raffaem** [comment]
Invalid report.

`indentifier` must be list.

Closing
