### ISSUE TITLE
[BUG] Papers with no citations will raise exception when calling `cc` on CitationOverview result

### ISSUE THREAD

**Issue by raffaem** [pybliometrics-dev/pybliometrics#205]
The following MWE:

```
from pybliometrics.scopus import CitationOverview
res = CitationOverview(identifier=["85098969104"], start=2020)
print(res.cc)
```

will throw the following exception:
```
$ python3 bug.py
Traceback (most recent call last):
  File "/run/media/raffaele/55ab61c4-83cf-4d9f-a5cd-7fcfdc14b4fb/data/phd/migliore_accademici/5_download_citations/bug.py", line 3, in <module>
    print(res.cc)
  File "/home/raffaele/.local/lib/python3.9/site-packages/pybliometrics/scopus/abstract_citation.py", line 44, in cc
    cites = [int(d['$']) for d in doc['cc']]
  File "/home/raffaele/.local/lib/python3.9/site-packages/pybliometrics/scopus/abstract_citation.py", line 44, in <listcomp>
    cites = [int(d['$']) for d in doc['cc']]
TypeError: string indices must be integers
```

**Comment by raffaem** [comment]
The bug also happens with papers with one citation.

MWE:
```
from pybliometrics.scopus import CitationOverview
res = CitationOverview(identifier=["85100910856"], start=2020)
print(res.grandTotal)
print(res.cc)
```

**Comment by raffaem** [comment]
It's *not true* that all papers with no citations will throw this error either. 

This paper has no citations and yet it doesn't throw the error:
```
>>> res = CitationOverview(identifier=["28844466437"], start=2005)
>>> print(res.grandTotal)
0
>>> res.cc
[[(2005, 0), (2006, 0), (2007, 0), (2008, 0), (2009, 0), (2010, 0), (2011, 0), (2012, 0), (2013, 0), (2014, 0), (2015, 0), (2016, 0), (2017, 0), (2018, 0), (2019, 0), (2020, 0), (2021, 0)]]
```

**Comment by Michael-E-Rose** [comment]
The first two example work fine for me. Which pybliometrics version are you using and which OS are you running on?

**Comment by Michael-E-Rose** [comment]
Still no error on my side.

Could you try to locate the cache file for case 1 and post its content here, please?
