### ISSUE TITLE
Cannot install from repo: versioning problem

### ISSUE THREAD

**Issue by raffaem** [pybliometrics-dev/pybliometrics#237]
```
git clone https://github.com/pybliometrics-dev/pybliometrics
cd pybliometrics
python setup.py install
```

```
C:\Users\rdpclient\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py:717: UserWarning: Usage of dash-separated 'author-email' will not be supported in future versions. Please use the underscore name 'author_email' instead
  warnings.warn(
C:\Users\rdpclient\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py:717: UserWarning: Usage of dash-separated 'maintainer-email' will not be supported in future versions. Please use the underscore name 'maintainer_email' instead
  warnings.warn(
C:\Users\rdpclient\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
  warnings.warn(
C:\Users\rdpclient\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py:717: UserWarning: Usage of dash-separated 'home-page' will not be supported in future versions. Please use the underscore name 'home_page' instead
  warnings.warn(
ERROR:root:Error parsing
Traceback (most recent call last):
  File "C:\Users\rdpclient\AppData\Local\Programs\Python\Python310\lib\site-packages\pbr\core.py", line 96, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "C:\Users\rdpclient\AppData\Local\Programs\Python\Python310\lib\site-packages\pbr\util.py", line 272, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "C:\Users\rdpclient\AppData\Local\Programs\Python\Python310\lib\site-packages\pbr\hooks\__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "C:\Users\rdpclient\AppData\Local\Programs\Python\Python310\lib\site-packages\pbr\hooks\base.py", line 27, in run
    self.hook()
  File "C:\Users\rdpclient\AppData\Local\Programs\Python\Python310\lib\site-packages\pbr\hooks\metadata.py", line 25, in hook
    self.config['version'] = packaging.get_version(
  File "C:\Users\rdpclient\AppData\Local\Programs\Python\Python310\lib\site-packages\pbr\packaging.py", line 874, in get_version
    raise Exception("Versioning for this project requires either an sdist"
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name pybliometrics was given, but was not able to be found.
error in setup command: Error parsing D:\data_RM\pybliometrics\setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name pybliometrics was given, but was not able to be found.
```

**Comment by raffaem** [comment]
`git` was not in PATH. Putting `git` in `PATH` fixes it. (the warnings for the dashes remain)
