### ISSUE TITLE
Scopus401Error instead of ScopusQueryError for ScopusSearch(..., subscriber=False)

### ISSUE THREAD

**Issue by Imankulov-ruslan** [pybliometrics-dev/pybliometrics#268]
Hi, i used 'subscriber=False' parameter but i have 401 error while executing the request below. Could you please clarify what is wrong?

```
from pybliometrics.scopus import ScopusSearch
ab = ScopusSearch('Morgan State University', subscriber=False)
print(ab)
```
But the following works for me

```
from pybliometrics.scopus import ScopusSearch
ab = ScopusSearch('Innopolis', subscriber=False)
print(ab)
```

**Comment by Michael-E-Rose** [comment]
Could you please share the entire error message?

Because I get a different error code: `pybliometrics.scopus.exception.ScopusQueryError: Found 1,308,430 matches.  The query fails to return more than 5000 entries.  Change your query such that it returns fewer entries.`

**Comment by Imankulov-ruslan** [comment]
(env) C:\Users\ruslan.imankulov\Desktop\Education\PY test course> c: && cd "c:\Users\ruslan.imankulov\Desktop\Education\PY test course" && cmd /C ""c:\Users\ruslan.imankulov\Desktop\Education\PY test course\env\Scripts\python.exe" c:\Users\ruslan.imankulov\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher 56629 -- "c:\Users\ruslan.imankulov\Desktop\Education\PY test course\tests\biblio.py" "
Traceback (most recent call last):
  File "c:\Users\ruslan.imankulov\Desktop\Education\PY test course\tests\biblio.py", line 4, in <module>
    ab = ScopusSearch('Morgan State University', subscriber=False)
  File "c:\Users\ruslan.imankulov\Desktop\Education\PY test course\env\lib\site-packages\pybliometrics\scopus\scopus_search.py", line 206, in __init__
    Search.__init__(self, query=query, api='ScopusSearch', count=count,
  File "c:\Users\ruslan.imankulov\Desktop\Education\PY test course\env\lib\site-packages\pybliometrics\scopus\superclasses\search.py", line 62, in __init__
    Base.__init__(self, params=params, url=URLS[api], download=download,
  File "c:\Users\ruslan.imankulov\Desktop\Education\PY test course\env\lib\site-packages\pybliometrics\scopus\superclasses\base.py", line 59, in __init__
    resp = get_content(url, api, params, *args, **kwds)
  File "c:\Users\ruslan.imankulov\Desktop\Education\PY test course\env\lib\site-packages\pybliometrics\scopus\utils\get_content.py", line 111, in get_content
    raise errors[resp.status_code](reason)
pybliometrics.scopus.exception.Scopus401Error: Invalid API Key

**Comment by Michael-E-Rose** [comment]
Thanks. I think you don't get the error message that is indented. The error message you should get is the one above, telling you you have too many results.

I'll look into that, but not this month.

**Comment by Imankulov-ruslan** [comment]
Looks like it was a problem with my API key
