### ISSUE TITLE
SerialTitle(..., view='CITESCORE') yields TypeError

### ISSUE THREAD

**Issue by Michael-E-Rose** [pybliometrics-dev/pybliometrics#364]
There's something wrong with the `SerialTitle()` class when using the `'CITESCORE'` view in the current python version:

```python
from pybliometrics.scopus import SerialTitle, init
init()
neural_networks = SerialTitle('1879-2782', view='CITESCORE', refresh=30)
neural_networks.citescoreyearinfolist[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\WorkingDir\Software\pybliometrics\pybliometrics\scopus\serial_title.py", line 58, in citescoreyearinfolist
    new_data = _get_all_cite_score_years(self, info_full, rank, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _get_all_cite_score_years() takes 3 positional arguments but 4 were given
```

**Comment by Michael-E-Rose** [comment]
Fixed with ad7113bbf9e112f9e07f68d70cb4f6f2190c0a4d
